<script setup lang="ts">
// components
import ComponentShower from '@/components/ComponentShower.vue';
import ComponentShowerRow from '@/components/ComponentShowerRow.vue';
import PropsAndEmitsShower from '@/components/PropsAndEmitsShower.vue';
// data
import { propsAndEmits } from '@/props-and-emits';
</script>

<template lang="pug">
ComponentShower(title="Default")
  ck-icon(icon="helicopter")
ComponentShower(title="Size")
  ComponentShowerRow(title="xs | s | m | l | xl")
    ck-icon(icon="user" size="xs")
    ck-icon(icon="user" size="s")
    ck-icon(icon="user" size="m")
    ck-icon(icon="user" size="l")
    ck-icon(icon="user" size="xl")
  ComponentShowerRow(title="xN")
    ck-icon(icon="user" size="1x")
    ck-icon(icon="user" size="2x")
    ck-icon(icon="user" size="3x")
    ck-icon(icon="user" size="4x")
    ck-icon(icon="user" size="5x")
ComponentShower(title="Color")
  ck-icon(icon="user" size="2x")
  ck-icon(icon="user" size="2x" color="primary")
  ck-icon(icon="user" size="2x" color="primary")
  ck-icon(icon="user" size="2x" color="primary-light")
  ck-icon(icon="user" size="2x" color="secondary")
  ck-icon(icon="user" size="2x" color="secondary-light")
  ck-icon(icon="user" size="2x" color="success")
  ck-icon(icon="user" size="2x" color="danger")
  ck-icon(icon="user" size="2x" color="warning")
  ck-icon(icon="user" size="2x" color="dark")
  ck-icon(icon="user" size="2x" color="light")
  ck-icon(icon="user" size="2x" color="unset")
ComponentShower(title="Movements")
  ComponentShowerRow(title="spin")
    ck-icon(icon="bullhorn" spin)
    ck-icon(icon="spinner" spin)
    ck-icon(icon="rotate" spin)
    ck-icon(icon="rotate-right" spin)
    ck-icon(icon="arrow-down" spin)
    ck-icon(icon="circle-arrow-down" spin)
  ComponentShowerRow(title="pulse")
    ck-icon(icon="bullhorn" pulse)
    ck-icon(icon="spinner" pulse)
    ck-icon(icon="rotate" pulse)
    ck-icon(icon="rotate-right" pulse)
    ck-icon(icon="arrow-down" pulse)
    ck-icon(icon="circle-arrow-down" pulse)
ComponentShower(title="Flip")
  ComponentShowerRow(title="common")
    ck-icon(icon="bullhorn" size="2x")
    ck-icon(icon="crow" size="2x")
    ck-icon(icon="shrimp" size="2x")
    ck-icon(icon="dove" size="2x")
    ck-icon(icon="spider" size="2x")
    ck-icon(icon="frog" size="2x")
  ComponentShowerRow(title="horizontal")
    ck-icon(icon="bullhorn" flip="horizontal" size="2x")
    ck-icon(icon="crow" flip="horizontal" size="2x")
    ck-icon(icon="shrimp" flip="horizontal" size="2x")
    ck-icon(icon="dove" flip="horizontal" size="2x")
    ck-icon(icon="spider" flip="horizontal" size="2x")
    ck-icon(icon="frog" flip="horizontal" size="2x")
  ComponentShowerRow(title="vertical")
    ck-icon(icon="bullhorn" flip="vertical" size="2x")
    ck-icon(icon="crow" flip="vertical" size="2x")
    ck-icon(icon="shrimp" flip="vertical" size="2x")
    ck-icon(icon="dove" flip="vertical" size="2x")
    ck-icon(icon="spider" flip="vertical" size="2x")
    ck-icon(icon="frog" flip="vertical" size="2x")
  ComponentShowerRow(title="both")
    ck-icon(icon="bullhorn" flip="both" size="2x")
    ck-icon(icon="crow" flip="both" size="2x")
    ck-icon(icon="shrimp" flip="both" size="2x")
    ck-icon(icon="dove" flip="both" size="2x")
    ck-icon(icon="spider" flip="both" size="2x")
    ck-icon(icon="frog" flip="both" size="2x")
ComponentShower(title="Rotation")
  ComponentShowerRow(title="Rotation: 0°, 90°, 180°, 270°")
    ck-icon(icon="arrow-up" rotation="0")
    ck-icon(icon="arrow-up" rotation="90")
    ck-icon(icon="arrow-up" rotation="180")
    ck-icon(icon="arrow-up" rotation="270")
ComponentShower(title="fixedWidth")
  ck-icon(icon="bullhorn" fixedWidth)
  ck-icon(icon="bullhorn" fixedWidth)
  ck-icon(icon="bullhorn" fixedWidth)

PropsAndEmitsShower(
:propsList="propsAndEmits.icon.props"
:emitsList="propsAndEmits.icon.emits"
)
</template>
